#!/usr/bin/env python3

import sys
import argparse
import postfix_mta_sts_resolver.utils as utils
from postfix_mta_sts_resolver.enums import *
import postfix_mta_sts_resolver.defaults as defaults
import netstring


def parse_args():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v", "--verbosity",
                        help="logging verbosity",
                        type=LogLevel.__getitem__,
                        choices=list(LogLevel),
                        default=LogLevel.warn)
    parser.add_argument("-c", "--config",
                        help="config file location",
                        metavar="FILE",
                        default=defaults.CONFIG_LOCATION)

    return parser.parse_args()


def main():
    args = parse_args()
    mainLogger = utils.setup_logger('MAIN', args.verbosity)
    mainLogger.info("MTA-STS daemon starting...")


if __name__ == '__main__':
    main()
