name: postfix-mta-sts-resolver
version: '1.3.0'
summary: Policy-server for Postfix which handles MTA-STS resolving
description: |
  Daemon which provides TLS client policy for Postfix via socketmap, 
  according to domain MTA-STS policy.
confinement: strict
base: core18

parts:
  extras:
    plugin: python
    python-version: python3
    python-packages:
      - "aiosqlite>=0.10.0"
      - "redis>=4.2.0rc1"
    build-packages:
      - gcc
      - make
      - python3-dev
      - libffi-dev
  postfix-mta-sts-resolver:
    plugin: python
    python-version: python3
    source: .
    build-packages:
      - gcc
      - make
      - python3-dev
      - libffi-dev

apps:
  daemon:
    command: bin/mta-sts-daemon
    plugs:
      - network
      - network-bind
  query:
    command: bin/mta-sts-query
    plugs:
      - network
